### ISSUE TITLE
new req for dumping CommandLineTools inputs into a "cwl.input.json" file

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwl-v1.3#15]
- does the `cwl.input.json` file go in the working directory?
- If so, how does this interact with `InitialWorkDirRequirement`?

Possible example:

Before:

``` yaml
requirements:
  InlineJavascriptRequirement: {}
  InitialWorkDirRequirement:
    listing:
      - entryname: cwl_inputs.json
        entry: $(JSON.stringify(inputs))
arguments:
  - -ini
  - cwl_inputs.json
```

After: 
``` yaml
requirements:
  InputsAsJson: {}  # default name is "cwl.input.json"
arguments:
  - -ini
  - cwl.input.json
```
or very concisely, perhaps:
``` yaml
arguments:
  - -ini
  - ${InputAsJson}  # resolves to a random filename not in the current working directory
```
