### ISSUE TITLE
parameter and step groups

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-v1.3#35]
Want to be able to apply annotations to groups of parameters or workflow steps.  This would principally be metadata documentation -- need to decide if this should include features that affect runtime execution or not.  The  goal is to have a way to provide better documentation & user interface for tool use.

Syntax options:

```
inputs:
  parameter1: string
  parameter: int
groups:
  group1:
    groupMembers: [parmeter1, parameter2]
    doc: "parameters related to the foobar feature"
```

```
inputs:
  parameter1:
    type: string
    groupMember: group1
  parameter:
    type: int
    groupMember: group1
groups:
  group1:
    doc: "parameters related to the foobar feature"
```

# Discussion points

* Can an item be a member of more than one group?
* Should it be possible for groups to be members of other groups?
* What kind of metadata should be specified?
* Are groups the appropriate place to declare dependencies between inputs, for example if optional input A is specified then optional input B is actually required
** The user guide describes option groups using records and unions but nobody uses that in practice

**Comment by tetron** [comment]
Groups should have a field called "expanded" (default true) which indicates if the group is expanded in the UI by default.

Groups should be displayed _after_ any non-grouped items.

**Comment by t0mdavid-m** [comment]
I think this is an important issue. I agree that groups are necessary for UI applications. My personal preference would be the first syntax suggestion. I believe the second option could be a bit confusing to work with.

**Comment by mr-c** [comment]
Here is an example of option one as an extension

``` cwl
$namespaces:
  cwltool: "http://commonwl.org/cwltool#"

inputs:
  parameter1: string
  parameter2: int
cwltool:groups:
  group1:
    groupMembers: [parmeter1, parameter2]
    doc: "parameters related to the foobar feature"
```

**Comment by mr-c** [comment]
@t0mdavid-m I updated the example in https://github.com/common-workflow-language/cwl-v1.3/issues/35#issuecomment-2507879501 to use the new syntax

**Comment by mr-c** [comment]
Open question from a discussion with @mvdbeek 

is `groups` mixed, for groups of inputs, groups of outputs, and (in case of a `class: Workflow`) groups of steps?
(with either a tricky schema enhancement or higher-level code to enforce that the `groupMembers` are all IDs from the same type)

or are there 3 top level entries, `inputGroups`, `outputGroups`, and `stepGroups`?

**Comment by tetron** [comment]
> New idea for the native (non-extension) syntax: specifying directly as part of the inputs or outputs using a type: group fake input/output.

:-1: this seems very awkward.

> or are there 3 top level entries, inputGroups, outputGroups, and stepGroups?

I think we do want to this, but for a different reason: for schema-salad to generically validate cross-references, we need to at least distinguish between steps and parameters, and if we fix the naming collision between inputs/outputs in the future (by prefixing the ids that get assigned) then we'll also need separate inputGroups and outputGroups.

Revised proposal:

```
inputs:
  parameter1: string
  parameter2: int
inputGroups:
  - group1:
      groupMembers: [parmeter1, parameter2]
      expanded: true
      doc: "parameters related to the foobar feature"
```

**Comment by mr-c** [comment]
> `inputGroups` and `groupMembers` are both explicitly ordered. See [#62 (comment)](https://github.com/common-workflow-language/cwl-v1.3/issues/62#issuecomment-2511762713) for discussion about ordered maps in YAML.

Yes, that is good, but there is a (reasonable, IMO) user request to preserve the order of inputs or outputs between the YAML file and any UI interface that is made using them. Regardless if those inputs are in a group or not.

**Comment by mr-c** [comment]
> > New idea for the native (non-extension) syntax: specifying directly as part of the inputs or outputs using a type: group fake input/output.
> 
> 👎 this seems very awkward.

Why? Because of the fake `type`?

**Comment by tetron** [comment]
> Why? Because of the fake `type`?

I think I misunderstood the proposal.  What you're saying is that the input parameters are `first_input`, `parameter1`, `parameter2`, and `other_input`, e.g. the input object would still be

```
first_input: 5
parameter1: "hello"
parameter2: 10
other_input:
  class: File
  location: http://example.com/file.jpg
```

Using the proposed sequence syntax and adding in `label` and `expanded` here's what it would look like:

```
inputs:
- first_input: int
- advanced_params:
     type: group
     label: "Advanced parameters"
     doc: "Advanced parameters related to the foobar feature"
     expanded: false
     members:
     - parameter1: string
     - parameter2: int
- other_input: File
```

This does feel a bit easier to understand for the end user.  On the other hand, embedding groups into the input definition like this means it is no longer an external annotation.  This means both the validation code and any code that walks over the list of inputs has to be able to handle groups.  So it is a much bigger change for implementers.  (which is why the original proposal defined groups separately).
