### ISSUE TITLE
move SchemaDef to top level

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-v1.3#38]
SchemaDefRequirement is awkward to use.

Propose moving the content of SchemaDefRequirement to document top level (same level as CommandLineTool/Workflow etc).  The requirement is no longer necessary, and parameters can just refer to types at arbitrary URIs provided they are resolvable.

```
$graph:
 - name: FooRecord
   type: record
   fields:
    foo: string
    bar: int

- id: Bar
  class: CommandLineTool
  inputs:
    param1: FooRecord
```

For discussion:

* How to disentangle 'inputBinding' for these types?  (Maybe define a new set of types that are compatible but not directly the same, that don't include inputBinding)
* Do we want to follow references to type definitions without needing an explicit import?
