### ISSUE TITLE
Way to specify step dependencies and output which are not included in the input/output

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-v1.3#41]
To help with reshaping inputs and outputs, it would be helpful to be able to specify input sources or output parameters which are not propagated to the actual input or output object.  This gives the user a way to inform the workflow checker that the input parameter isn't expected to match the signature of the underlying 'run', and doesn't  pass through parameters to the underlying 'run' which may be problematic.

I believe it is the case that cwltool already does not pass through input object elements that do not match the signature, but this would make it formally specified.

- [ ]  need to decide on the name

Example:

```
  in:
      render: { source: render, propagate: false }
      source: {valueFrom: $(inputs.render.source)}
      target: {valueFrom: $(inputs.render.target)}
      renderlist: {valueFrom: $(inputs.render.renderlist)}

```
